# Generated by Django 4.2.8 on 2025-06-10 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 10, 14, 16, 26, 819555, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
